### PR TITLE
Module readme tool

### PR DESCRIPTION
**Pull request by TheJosh**
See this mailing list topic:
http://lists.freedesktop.org/archives/libreoffice/2012-February/025198.html

### CODE REVIEW

**Comment by cloph** [comment]
sorry for not replying earlier - i thought I'd get notifications automatically when being member of the organization, but apparently you need to create a team first and add yourself to that team to receive notifications.

My understanding of the thread is that it got integrated into the main libreoffice.org repository. Is adding it to the misc repo still requested? If so, please leave a short reply and I'll merge it.

**Comment by TheJosh** [comment]
Nope, it isn't in the main repo, that's the READMEs for the modules, the code for doing the pretty display is here.

**Comment by TheJosh** [comment]
Never mind me, I am mistaken.

**Comment by cloph** [comment]
thanks for the folluw-up, closing then. Thanks a lot for your work :-)

**Pull request closed without merging**
